### ISSUE TITLE
Request for the data used in HiCiPSC workflow

### ISSUE THREAD

**Issue by kevinCate** [IttaiEres/HiCiPSC#1]
Hi, 

I'm quite interseted in the R workflow used to generate figures in your paper, and I want to go through your pipeline for the practice of cross-species Hi-C comparison. However, I can't find the files you read in in the workflow (e.g. data/final.10kb.homer.df in the first section). It's difficult for me to interpret your result only from the code. Could you please provide me with such kind of data?  Any suggestion will be appreciated.

Thank you in advance.

**Comment by IttaiEres** [comment]
Unfortunately those files are too large to upload to github (beyond the size limit). If you need an example of their formatting that is available [here](https://github.com/IttaiEres/HiCiPSC/blob/master/final.10kb.homer.df.sample). If you are interested in the entire file, please feel free to contact me via gmail (my address is simple and can be inferred from my github username), and I can share a google drive link with you.

Thanks,
Ittai
